# fly.toml app configuration file generated for rac-streamer on 2024-06-27T10:25:04+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rac-streamer'
primary_region = 'sin'

[build]

[[vm]]
  size = "shared-cpu-2x"
  memory = '1gb'
